title: HueCodes
description: Hugh's personal site. Systems, embedded robotics, networking, hardware, and ml tooling.
url: "https://huecodes.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge

permalink: /blog/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

collections:
  projects:
    output: true
    permalink: /projects/:name/
  hardware:
    output: true
    permalink: /hardware/:name/
  research:
    output: true
    permalink: /research/:name/
